In [1]:
# import packages
import pandas as pd
import requests
pd.set_option('display.max_columns', None) # so we can see all columns in a wide dataframe
import time
import numpy as np

In [2]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2012-13&SeasonType=Regular%20Season&StatCategory=PTS'

In [3]:
r = requests.get(url=test_url).json()

In [4]:
table_headers = r['resultSet']['headers']

In [5]:
pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,203130,463,Darius Johnson-Odom,1610612747,LAL,4,6,0,4,0.000,0,1,0.000,0,0,0.000,1,3,4,1,0,0,0,0,0,1,0.00,0.00
464,2545,463,Darko Milicic,1610612738,BOS,1,5,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,2,1,0,-2,0.00,0.00
465,202458,463,Justin Dentmon,1610612742,DAL,2,4,0,2,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
466,2679,463,Matt Carroll,1610612766,CHA,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,1,0,1,0.00,0.00
467,200780,463,Solomon Jones,1610612752,NYK,2,26,0,1,0.000,0,0,0.000,0,0,0.000,1,2,3,0,0,1,3,3,0,0,0.00,0.00

In [6]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
temp_df2 = pd.DataFrame({'Year':['2012-13' for i in range(len(temp_df1))],
                        'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2,temp_df1], axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2012-13,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,2012-13,Regular%20Season,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2012-13,Regular%20Season,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,2012-13,Regular%20Season,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2012-13,Regular%20Season,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,2012-13,Regular%20Season,203130,463,Darius Johnson-Odom,1610612747,LAL,4,6,0,4,0.000,0,1,0.000,0,0,0.000,1,3,4,1,0,0,0,0,0,1,0.00,0.00
464,2012-13,Regular%20Season,2545,463,Darko Milicic,1610612738,BOS,1,5,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,2,1,0,-2,0.00,0.00
465,2012-13,Regular%20Season,202458,463,Justin Dentmon,1610612742,DAL,2,4,0,2,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
466,2012-13,Regular%20Season,2679,463,Matt Carroll,1610612766,CHA,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,1,0,1,0.00,0.00
467,2012-13,Regular%20Season,200780,463,Solomon Jones,1610612752,NYK,2,26,0,1,0.000,0,0,0.000,0,0,0.000,1,2,3,0,0,1,3,3,0,0,0.00,0.00

In [7]:
del temp_df1, temp_df2, temp_df3

In [8]:
df_cols = ['Year', 'Season_type'] + table_headers # Combine your new columns with existing headers

In [9]:
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [10]:
headers = {
    'Accept':'*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Origin': 'https://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'Sec-Ch-Ua': '"Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': "Windows",
    'Sec-Fetch-Dest':'empty',
    'Sec-Fetch-Mode':'cors',
    'Sec-Fetch-Site':'same-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
}

In [11]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = f'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season={y}&SeasonType={s}&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        
        # Check if 'resultSet' is in the response
        if 'resultSet' in r and 'rowSet' in r['resultSet']:
            temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
            temp_df2 = pd.DataFrame({'Year': [y] * len(temp_df1),
                                     'Season_type': [s] * len(temp_df1)})
            temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
            df = pd.concat([df, temp_df3], axis=0)
            print(f'Completed {y} {s}')
        else:
            print(f'No data for {y} {s}')
        
        # add a lag to avoid being flagged as a bot
        lag = np.random.uniform(low=5, high=20)
        print(f'.... waiting for {round(lag,1)} seconds')
        time.sleep(lag)

print(f'Process completed! Total runtime: {round((time.time()-begin_loop)/60,2)} minutes')
df.to_csv('nba_player_data.csv', index=False)

C:\Users\Joseph\AppData\Local\Temp\ipykernel_16612\1966947650.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis=0)

Completed 2012-13 Regular%20Season
.... waiting for 10.0 seconds
Completed 2012-13 Playoffs
.... waiting for 17.0 seconds
Completed 2013-14 Regular%20Season
.... waiting for 12.5 seconds
Completed 2013-14 Playoffs
.... waiting for 9.3 seconds
Completed 2014-15 Regular%20Season
.... waiting for 16.8 seconds
Completed 2014-15 Playoffs
.... waiting for 19.3 seconds
Completed 2015-16 Regular%20Season
.... waiting for 17.5 seconds
Completed 2015-16 Playoffs
.... waiting for 14.0 seconds
Completed 2016-17 Regular%20Season
.... waiting for 15.0 seconds
Completed 2016-17 Playoffs
.... waiting for 11.5 seconds
Completed 2018-19 Regular%20Season
.... waiting for 9.9 seconds
Completed 2018-19 Playoffs
.... waiting for 6.1 seconds
Completed 2019-20 Regular%20Season
.... waiting for 16.5 seconds
Completed 2019-20 Playoffs
.... waiting for 15.9 seconds
Completed 2020-21 Regular%20Season
.... waiting for 16.3 seconds
Completed 2020-21 Playoffs
.... waiting for 11.7 seconds
Completed 2021-22 Regular%20Season
.... waiting for 14.7 seconds
Completed 2021-22 Playoffs
.... waiting for 13.1 seconds
Completed 2022-23 Regular%20Season
.... waiting for 17.0 seconds
Completed 2022-23 Playoffs
.... waiting for 18.6 seconds
Completed 2023-24 Regular%20Season
.... waiting for 13.2 seconds
Completed 2023-24 Playoffs
.... waiting for 12.7 seconds
Process completed! Total runtime: 5.4 minutes

In [12]:
df

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2012-13,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,2012-13,Regular%20Season,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2012-13,Regular%20Season,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,2012-13,Regular%20Season,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2012-13,Regular%20Season,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2023-24,Playoffs,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.000,0,0,0.000,0,0,0.000,0,3,3,1,0,0,0,0,0,2,0.00,0.00
210,2023-24,Playoffs,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
211,2023-24,Playoffs,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
212,2023-24,Playoffs,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,2023-24,Playoffs,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00